name: Backend testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v3
    - name: Set up Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies and Python
      run: |
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest
